### PR TITLE
Add a workflow to automatically add issues and PRs to my maintenance GH project

### PR DESCRIPTION
**Pull request by jdhoffa**
I have created a GitHub project board here to track all issues and PRs across all of the repositories I maintain:
https://github.com/orgs/RMI-PACTA/projects/12

This PR adds a workflow that automatically adds issues and PRs to that project. 

Adapted from @cjyetman's action. 

FYI @RMI-PACTA/developers in case you find this useful or interesting. Ping me if you would like an explanation of this.

### CODE REVIEW

**Comment by cjyetman** [comment]
I will likely do exactly the same for the repos I maintain, as well as (maybe) maintain the board I have used in the past for all TM related repos.

**Comment by jdhoffa** [comment]
> I will likely do exactly the same for the repos I maintain, as well as (maybe) maintain the board I have used in the past for all TM related repos.

Then we can trade PR review spamming 😂

**Comment by jdhoffa** [comment]
@cjyetman last one :-)

**Review by cjyetman — APPROVED** [review]

**Comment by MonikaFu** [comment]
Looks interesting. I want it too.

**Comment by jdhoffa** [comment]
I can show you how to do it, but you're gonna have to set it up yourself ;-) hahaha

**Pull request merged**
