### PR TITLE
Fix demo data

### PR DESCRIPTION
**Pull request by jacobvjk**
This PR:
- reverts to a version of the previous `loanbook_demo` and `abcd_demo` data sets
- this is needed because the updated demo data has a few issues regarding the compatibility of its format with standard P4B banks abcd
- additionally, I removed `year`s in the `abcd_demo` data set that fall outside of the t0 - t5 range, as these are not provided in the standard banks data set and would require additional manual filtering when using the demo data
- I also changed the `abcd_timestamp` to `2020Q4` which would be more realistic given the years available in the demo data set
- standard P4B workflows (loading demo data, simple matching, loanbook and company level calculation plus plots) generate as expected with this data
- two additional loans were added to the `loanbook_demo` data, containing counterparties that are already available in `abcd_demo`. this is to ensure we have loans matching each in scope sector in the `loanbook_demo`

### CODE REVIEW

**Review by Antoine-Lalechere — DISMISSED** [review]
LGTM

**Review by cjyetman — APPROVED** [review]
Trusting you on this because I have no idea really. Don't see any syntactical problems. Hope George is aware because he would likely be the most concerned about this.

**Comment by cjyetman** [comment]
Also, I would make sure @AlexAxthelm is aware of this, because he's in the process of getting new versions of packages that rely on this package onto CRAN, and as I understood, the new data here was a necessary dependence.

**Comment by jacobvjk** [comment]
> Trusting you on this because I have no idea really. Don't see any syntactical problems. Hope George is aware because he would likely be the most concerned about this.

He absolutely is aware, this has been discussed widely until we decided to temporarily roll back

**Review by AlexAxthelm — DISMISSED** [review]
@jacobvjk Please check against the latest versions on CRAN, but this looks good by me otherwise.

**Comment by jacobvjk** [comment]
> @jacobvjk Please check against the latest versions on CRAN, but this looks good by me otherwise.

Yes, the checks pass with recent CRAN releases of r2dii.match and r2dii.analysis. I bumped the package version as well, so will need another approval to merge

**Comment by cjyetman** [comment]
> Yes, the checks pass with recent CRAN releases of r2dii.match and r2dii.analysis. I bumped the package version as well, so will need another approval to merge

I think what's more relevant is if current/release versions of r2dii.match and r2dii.analysis pass their tests using the version of data in this PR

**Comment by jacobvjk** [comment]
> > Yes, the checks pass with recent CRAN releases of r2dii.match and r2dii.analysis. I bumped the package version as well, so will need another approval to merge
> 
> I think what's more relevant is if current/release versions of r2dii.match and r2dii.analysis pass their tests using the version of data in this PR

the checks for both still pass and I have tested the demo data with the lates cran releases locally too

**Review by cjyetman — APPROVED** [review]

**Pull request merged**
